export {
    createProductType,
    createProductTypeAttribute,
    createProductTypeOption,
    deleteProductType,
    deleteProductTypeAttribute,
    deleteProductTypeOption,
    getProductTypeAttributeById,
    getProductTypeAttributes,
    getProductTypeById,
    getProductTypeBySlug,
    getProductTypeOptions,
    getProductTypes,
    updateProductType,
    updateProductTypeAttribute,
    updateProductTypeOption,
} from './api';

export type {
    CreateProductTypeAttributeInput,
    CreateProductTypeInput,
    CreateProductTypeOptionInput,
    ProductAttributeScope,
    ProductAttributeType,
    ProductType,
    ProductTypeAttribute,
    ProductTypeAttributeOption,
    ProductTypeListResponse,
    UpdateProductTypeAttributeInput,
    UpdateProductTypeInput,
    UpdateProductTypeOptionInput,
} from './model/types';
